# Generated by Django 2.0.3 on 2018-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_id', models.CharField(max_length=32)),
                ('project_id', models.IntegerField()),
                ('message', models.TextField()),
                ('platform', models.CharField(max_length=64, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_spent', models.IntegerField(null=True)),
                ('data', models.BinaryField()),
            ],
        ),
    ]
