# Generated by Django 2.0.3 on 2018-03-31 21:10

from django.db import migrations, models
import minisentry.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=32, null=True)),
                ('event_id', models.CharField(max_length=32)),
                ('project_id', models.IntegerField()),
                ('message', models.TextField()),
                ('level', models.IntegerField(null=True)),
                ('platform', models.CharField(max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_spent', models.IntegerField(null=True)),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(default=minisentry.helpers.gen_secret, max_length=34)),
                ('secret', models.CharField(default=minisentry.helpers.gen_secret, max_length=34)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('project_id', 'event_id')},
        ),
        migrations.AlterIndexTogether(
            name='event',
            index_together={('group_id', 'timestamp')},
        ),
    ]
