# Generated by Django 2.0.3 on 2018-03-31 19:22

from django.db import migrations, models
import minisentry.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('minisentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(default=minisentry.helpers.gen_secret, max_length=34)),
                ('secret', models.CharField(default=minisentry.helpers.gen_secret, max_length=34)),
            ],
        ),
    ]
